"""
Географические данные и координаты филиалов, залов и региональных церквей KCLC
"""

CENTRAL_CHURCH = {
    'id': 'central-krasnoyarsk',
    'type': 'central',
    'type_label': 'Центральная церковь',
    'title': 'Церковь Христианской Жизни (Красноярск)',
    'city': 'Красноярск',
    'address': 'ул. Металлургов, 24Д',
    'pastors': 'Старший пастор Владимир Ашаев',
    'phone': '+7 (391) 220-40-50',
    'email': 'info@kclc.ru',
    'schedule': 'Воскресенье 11:00 (Богослужение)',
    'lat': 56.0573,
    'lng': 92.9644,
    'is_headquarters': True,
}

REGIONAL_BRANCHES = [
    {
        'id': 'branch-artem',
        'type': 'branch',
        'type_label': 'Региональная церковь',
        'title': 'Церковь Христианской Жизни — Артем',
        'city': 'г. Артем',
        'address': 'ул. Пушкина, 16',
        'pastors': 'Михаил и Анастасия Беспаловы',
        'phone': '8-914-965-98-85',
        'email': 'bmv1_1974@mail.ru',
        'schedule': 'Вс 10:30',
        'lat': 43.3553,
        'lng': 132.1764,
    },
    {
        'id': 'branch-barnaul',
        'type': 'branch',
        'type_label': 'Региональная церковь',
        'title': 'Церковь Христианской Жизни — Барнаул',
        'city': 'г. Барнаул',
        'address': 'ул. Челюскинцев, 80 (вход со двора)',
        'pastors': 'Елена Дробышевская',
        'phone': '8-963-500-80-32',
        'email': '',
        'schedule': 'Вс 12:00',
        'lat': 53.3377,
        'lng': 83.7749,
    },
    {
        'id': 'branch-boguchany',
        'type': 'branch',
        'type_label': 'Региональная церковь',
        'title': 'Церковь Христианской Жизни — Богучаны',
        'city': 'с. Богучаны',
        'address': 'ул. Садовая, 4',
        'pastors': 'Михаил и Светлана Зыряновы',
        'phone': '8-913-836-44-22',
        'email': 'mihail.zyryanov@gmail.com',
        'schedule': 'Вс 11:00',
        'lat': 58.3794,
        'lng': 97.4566,
    },
    {
        'id': 'branch-bratsk',
        'type': 'branch',
        'type_label': 'Региональная церковь',
        'title': 'Церковь Христианской Жизни — Братск',
        'city': 'г. Братск',
        'address': 'ул. Южная, 8 стр. 3, каб. 8',
        'pastors': 'Леонид и Татьяна Омельченко',
        'phone': '8-964-352-88-15',
        'email': '',
        'schedule': 'Вс 11:00',
        'lat': 56.1528,
        'lng': 101.6142,
    },
    {
        'id': 'branch-vladivostok',
        'type': 'branch',
        'type_label': 'Региональная церковь',
        'title': 'Церковь Христианской Жизни — Владивосток',
        'city': 'г. Владивосток',
        'address': 'пр. 100-летия Владивостока, 18',
        'pastors': 'Алексей и Валентина Моисеевы',
        'phone': '8-984-145-52-21',
        'email': 'clc.vladivostok@gmail.com',
        'schedule': 'Вс 11:00',
        'lat': 43.1612,
        'lng': 131.9067,
    },
    {
        'id': 'branch-zheleznogorsk',
        'type': 'branch',
        'type_label': 'Региональная церковь',
        'title': 'Церковь Христианской Жизни — Железногорск',
        'city': 'г. Железногорск',
        'address': 'ул. Матросова, 13 (2 этаж)',
        'pastors': 'Александр и Евгения Смирновы',
        'phone': '8-913-830-75-93',
        'email': '',
        'schedule': 'Вс 12:00',
        'lat': 56.2494,
        'lng': 93.5350,
    },
    {
        'id': 'branch-zelenogorsk',
        'type': 'branch',
        'type_label': 'Региональная церковь',
        'title': 'Церковь Христианской Жизни — Зеленогорск',
        'city': 'г. Зеленогорск',
        'address': 'ул. Гагарина, 10А',
        'pastors': 'Артур и Марина Матюшевские',
        'phone': '8-923-309-57-20',
        'email': '',
        'schedule': 'Вс 11:00',
        'lat': 56.1044,
        'lng': 94.5919,
    },
    {
        'id': 'branch-kaliningrad',
        'type': 'branch',
        'type_label': 'Региональная церковь',
        'title': 'Церковь Христианской Жизни — Калининград',
        'city': 'г. Калининград',
        'address': 'ул. Октябрьская 8, ДЦ «На острове», 2 этаж',
        'pastors': 'Роман и Софья Мозжерины',
        'phone': '8-923-346-46-46',
        'email': 'nehemia76@gmail.com',
        'schedule': 'Вс 11:00',
        'lat': 54.7074,
        'lng': 20.5186,
    },
    {
        'id': 'branch-kaluga',
        'type': 'branch',
        'type_label': 'Региональная церковь',
        'title': 'Церковь Христианской Жизни — Калуга',
        'city': 'г. Калуга',
        'address': 'пер. Воскресенский, 29 (конференц-зал)',
        'pastors': 'Владимир и Елена Ашаевы',
        'phone': '8-920-877-09-80',
        'email': '',
        'schedule': 'Вс 11:00',
        'lat': 54.5138,
        'lng': 36.2612,
    },
    {
        'id': 'branch-krasnodar',
        'type': 'branch',
        'type_label': 'Региональная церковь',
        'title': 'Церковь Христианской Жизни — Краснодар',
        'city': 'г. Краснодар',
        'address': 'ул. Дзержинского, 22/1',
        'pastors': 'Андрей и Ольга Лисовские',
        'phone': '8-918-124-77-99',
        'email': '',
        'schedule': 'Вс 11:00',
        'lat': 45.0601,
        'lng': 38.9749,
    },
    {
        'id': 'branch-minusinsk',
        'type': 'branch',
        'type_label': 'Региональная церковь',
        'title': 'Церковь Христианской Жизни — Минусинск',
        'city': 'г. Минусинск',
        'address': 'ул. Штабная, 18',
        'pastors': 'Виктор и Татьяна Плотниковы',
        'phone': '8-902-911-33-77',
        'email': '',
        'schedule': 'Вс 11:00',
        'lat': 53.7102,
        'lng': 91.6874,
    },
    {
        'id': 'branch-novosibirsk',
        'type': 'branch',
        'type_label': 'Региональная церковь',
        'title': 'Церковь Христианской Жизни — Новосибирск',
        'city': 'г. Новосибирск',
        'address': 'ул. Фрунзе, 5',
        'pastors': 'Сергей и Марина Ковалевы',
        'phone': '8-913-912-34-56',
        'email': '',
        'schedule': 'Вс 11:00',
        'lat': 55.0357,
        'lng': 82.9272,
    },
    {
        'id': 'branch-spb',
        'type': 'branch',
        'type_label': 'Региональная церковь',
        'title': 'Церковь Христианской Жизни — Санкт-Петербург',
        'city': 'г. Санкт-Петербург',
        'address': 'Лиговский проспект, 50',
        'pastors': 'Павел и Анна Новиковы',
        'phone': '8-981-800-22-11',
        'email': 'spb@kclc.ru',
        'schedule': 'Вс 12:00',
        'lat': 59.9271,
        'lng': 30.3609,
    },
    {
        'id': 'branch-sochi',
        'type': 'branch',
        'type_label': 'Региональная церковь',
        'title': 'Церковь Христианской Жизни — Сочи',
        'city': 'г. Сочи',
        'address': 'ул. Горького, 53',
        'pastors': 'Константин и Вера Семеновы',
        'phone': '8-988-233-44-55',
        'email': '',
        'schedule': 'Вс 11:00',
        'lat': 43.5855,
        'lng': 39.7231,
    },
    {
        'id': 'branch-khabarovsk',
        'type': 'branch',
        'type_label': 'Региональная церковь',
        'title': 'Церковь Христианской Жизни — Хабаровск',
        'city': 'г. Хабаровск',
        'address': 'ул. Карла Маркса, 62',
        'pastors': 'Роман и Евгения Беловы',
        'phone': '8-914-150-77-88',
        'email': '',
        'schedule': 'Вс 11:00',
        'lat': 48.4802,
        'lng': 135.0719,
    },
]

def get_all_map_locations(include_homegroups=True, include_events=True):
    """
    Формирует единый список меток для интерактивной карты.
    """
    from church_app.models import HomeGroup, Event

    locations = [CENTRAL_CHURCH] + REGIONAL_BRANCHES

    if include_homegroups:
        hgroups = HomeGroup.objects.filter(is_active=True).exclude(latitude__isnull=True).exclude(longitude__isnull=True)
        for hg in hgroups:
            locations.append({
                'id': f'homegroup-{hg.id}',
                'type': 'homegroup',
                'type_label': f'Домашняя группа ({hg.get_type_display()})',
                'title': f'Домашняя группа — {hg.district}',
                'city': 'Красноярск',
                'address': hg.address,
                'pastors': hg.leader_name or 'Лидер группы',
                'phone': hg.leader_phone or '',
                'telegram': hg.leader_telegram or '',
                'schedule': f'{hg.get_day_display()} {hg.time or ""}'.strip(),
                'age_display': hg.get_age_display(),
                'description': hg.description,
                'lat': hg.latitude,
                'lng': hg.longitude,
            })

    if include_events:
        events = Event.objects.filter(is_active=True).exclude(latitude__isnull=True).exclude(longitude__isnull=True)
        for ev in events:
            locations.append({
                'id': f'event-{ev.id}',
                'type': 'event',
                'type_label': 'Мероприятие',
                'title': ev.title,
                'city': ev.location,
                'address': ev.address or ev.location,
                'pastors': '',
                'phone': '',
                'schedule': ev.start_date.strftime('%d.%m.%Y в %H:%M'),
                'url': f'/events/{ev.slug}/' if ev.slug else '#',
                'is_online': ev.is_online,
                'lat': ev.latitude,
                'lng': ev.longitude,
            })

    return locations

