# Generated by Django 6.0.2 on 2026-02-09 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpiritualLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название уровня')),
                ('description', models.TextField(verbose_name='Описание')),
                ('level_type', models.CharField(choices=[('basic', 'Основы веры'), ('growth', 'Духовный рост'), ('service', 'Служение'), ('leadership', 'Лидерство')], default='basic', max_length=50)),
                ('order', models.IntegerField(verbose_name='Порядковый номер')),
                ('image', models.ImageField(blank=True, null=True, upload_to='levels/', verbose_name='Изображение')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Уровень духовного пути',
                'verbose_name_plural': 'Уровни духовного пути',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Пройден')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('progress_percentage', models.IntegerField(default=0, verbose_name='Процент выполнения')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church_app.spirituallevel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Прогресс пользователя',
                'verbose_name_plural': 'Прогресс пользователей',
                'unique_together': {('user', 'level')},
            },
        ),
    ]
