# Generated by Django 6.0.2 on 2026-02-12 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='announcements/', verbose_name='Изображение')),
                ('button_text', models.CharField(default='Узнать больше', max_length=100, verbose_name='Текст кнопки')),
                ('button_link', models.CharField(default='/news/', max_length=500, verbose_name='Ссылка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='spirituallevel',
            name='building_style',
            field=models.CharField(choices=[('church', 'Церковь'), ('chapel', 'Часовня'), ('cathedral', 'Собор'), ('monastery', 'Монастырь'), ('temple', 'Храм'), ('house', 'Дом'), ('library', 'Библиотека'), ('school', 'Школа')], default='church', max_length=50),
        ),
        migrations.AddField(
            model_name='spirituallevel',
            name='color',
            field=models.CharField(default='#3498db', max_length=20, verbose_name='Цвет здания'),
        ),
        migrations.AddField(
            model_name='spirituallevel',
            name='height',
            field=models.IntegerField(default=3, verbose_name='Высота здания'),
        ),
        migrations.AddField(
            model_name='spirituallevel',
            name='position_x',
            field=models.IntegerField(default=0, verbose_name='Позиция X'),
        ),
        migrations.AddField(
            model_name='spirituallevel',
            name='position_y',
            field=models.IntegerField(default=0, verbose_name='Позиция Y'),
        ),
        migrations.AlterField(
            model_name='spirituallevel',
            name='level_type',
            field=models.CharField(choices=[('basic', 'Основы веры'), ('growth', 'Духовный рост'), ('service', 'Служение'), ('leadership', 'Лидерство'), ('worship', 'Поклонение'), ('prayer', 'Молитва'), ('study', 'Изучение'), ('fellowship', 'Общение')], default='basic', max_length=50),
        ),
    ]
