# Generated by Django 6.0.2 on 2026-02-19 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0002_announcement_spirituallevel_building_style_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiblePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bible_plans/', verbose_name='Изображение')),
                ('days_count', models.IntegerField(default=7, verbose_name='Количество дней')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'План чтения',
                'verbose_name_plural': 'Планы чтения',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('category_type', models.CharField(choices=[('video', 'Видео'), ('bible', 'Чтение Библии'), ('events', 'События'), ('calendar', 'Календарь'), ('kids', 'Детский раздел')], max_length=20, verbose_name='Тип')),
                ('icon', models.CharField(default='fa-folder', max_length=50, verbose_name='Иконка FontAwesome')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('event_type', models.CharField(choices=[('service', 'Богослужение'), ('youth', 'Молодежка'), ('kids', 'Детское служение'), ('study', 'Библейский урок'), ('prayer', 'Молитвенное собрание'), ('special', 'Особое событие')], default='service', max_length=50, verbose_name='Тип события')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('location', models.CharField(max_length=200, verbose_name='Место проведения')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Изображение')),
                ('max_participants', models.IntegerField(default=0, help_text='0 = без ограничений', verbose_name='Макс. участников')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемое')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='KidsContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('content_type', models.CharField(choices=[('cartoon', 'Мультфильм'), ('lesson', 'Урок'), ('game', 'Игра'), ('craft', 'Поделка'), ('song', 'Песня')], max_length=20, verbose_name='Тип контента')),
                ('age_group', models.CharField(choices=[('3-5', '3-5 лет'), ('6-8', '6-8 лет'), ('9-12', '9-12 лет'), ('all', 'Все возрасты')], default='all', max_length=10, verbose_name='Возрастная группа')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='kids_videos/', verbose_name='Видео файл')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='YouTube ссылка')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='kids_thumbnails/', verbose_name='Превью')),
                ('bible_verse', models.CharField(blank=True, max_length=200, verbose_name='Библейский стих')),
                ('game_data', models.JSONField(blank=True, default=dict, verbose_name='Данные игры')),
                ('printable_material', models.FileField(blank=True, null=True, upload_to='kids_printables/', verbose_name='Материал для печати')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемое')),
                ('views_count', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Детский контент',
                'verbose_name_plural': 'Детский контент',
                'ordering': ['-is_featured', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видео файл')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='YouTube ссылка')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='video_thumbnails/', verbose_name='Превью')),
                ('duration', models.IntegerField(default=0, help_text='Длительность в секундах', verbose_name='Длительность')),
                ('views_count', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемое')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(limit_choices_to={'category_type': 'video'}, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='church_app.category')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
                'ordering': ['-is_featured', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BibleReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(verbose_name='День')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('bible_passage', models.CharField(max_length=200, verbose_name='Отрывок (например: Иоанна 3:16)')),
                ('start_chapter', models.CharField(help_text='Книга Глава:Стих', max_length=50, verbose_name='Начало')),
                ('end_chapter', models.CharField(blank=True, max_length=50, null=True, verbose_name='Конец')),
                ('content', models.TextField(blank=True, verbose_name='Дополнительный текст')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='church_app.bibleplan')),
            ],
            options={
                'verbose_name': 'День чтения',
                'verbose_name_plural': 'Дни чтения',
                'ordering': ['plan', 'day_number'],
                'unique_together': {('plan', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('attended', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='church_app.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Регистрация',
                'verbose_name_plural': 'Регистрации',
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.CreateModel(
            name='KidsProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(default=0, help_text='Для игр - очки', verbose_name='Результат')),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='church_app.kidscontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kids_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Прогресс ребенка',
                'verbose_name_plural': 'Прогресс детей',
                'unique_together': {('user', 'content')},
            },
        ),
        migrations.CreateModel(
            name='UserBibleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_day', models.IntegerField(default=0)),
                ('completed_days', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_read_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church_app.bibleplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bible_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Прогресс чтения',
                'verbose_name_plural': 'Прогресс чтения',
                'unique_together': {('user', 'plan')},
            },
        ),
    ]
