# Generated by Django 5.2.11 on 2026-04-02 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0003_bibleplan_category_event_kidscontent_video_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVerse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse_text', models.TextField(verbose_name='Текст стиха')),
                ('reference', models.CharField(max_length=100, verbose_name='Ссылка (напр. Иоанна 3:16)')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('reflection', models.TextField(blank=True, null=True, verbose_name='Короткое размышление')),
            ],
            options={
                'verbose_name': 'Стих дня',
                'verbose_name_plural': 'Стихи дня',
            },
        ),
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Тема молитвы')),
                ('description', models.TextField(verbose_name='Описание нужды')),
                ('is_answered', models.BooleanField(default=False, verbose_name='Получен ответ')),
                ('prayer_count', models.IntegerField(default=0, verbose_name='Сколько человек молится')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичная просьба')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Молитвенная нужда',
                'verbose_name_plural': 'Молитвенные нужды',
            },
        ),
    ]
