# Generated by Django 5.2.11 on 2026-04-13 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0007_donation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='level',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='SpiritualLevel',
        ),
        migrations.DeleteModel(
            name='UserProgress',
        ),
    ]
