# Generated by Django 5.2.11 on 2026-04-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0008_remove_userprogress_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Название (для админки)')),
                ('image', models.ImageField(upload_to='hero_backgrounds/', verbose_name='Изображение')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Фон главной страницы',
                'verbose_name_plural': 'Фоны главной страницы',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
