# Generated by Django 5.2.11 on 2026-04-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0009_herobackground'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobackground',
            name='link_url',
            field=models.CharField(blank=True, help_text='Например: /news/ или https://...', max_length=500, verbose_name='Ссылка для регистрации'),
        ),
    ]
