# Generated by Django 5.2.11 on 2026-04-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0011_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='rutube_url',
            field=models.URLField(blank=True, null=True, verbose_name='Rutube ссылка'),
        ),
    ]
