# Generated by Django 6.0.5 on 2026-08-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0013_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastorPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Идентификатор пастора')),
                ('image', models.ImageField(upload_to='pastors/', verbose_name='Фото')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Фото пастора',
                'verbose_name_plural': 'Фото пасторов',
            },
        ),
    ]
