# Generated by Django 6.0.5 on 2026-08-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0014_pastorphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastorphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pastors/', verbose_name='Фото'),
        ),
    ]
