# Generated by Django 6.0.5 on 2026-08-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0015_alter_pastorphoto_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100, verbose_name='Район')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('group_type', models.CharField(choices=[('mixed', 'Смешанная'), ('male', 'Мужская'), ('female', 'Женская'), ('youth', 'Молодежная'), ('teen', 'Подростковая')], default='mixed', max_length=20, verbose_name='Тип группы')),
                ('day', models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота'), ('sunday', 'Воскресенье'), ('negotiable', 'По договоренности')], default='negotiable', max_length=20, verbose_name='День недели')),
                ('time', models.CharField(blank=True, max_length=20, null=True, verbose_name='Время (например: 19:00)')),
                ('age_min', models.IntegerField(blank=True, default=0, null=True, verbose_name='Минимальный возраст')),
                ('age_max', models.IntegerField(blank=True, default=0, null=True, verbose_name='Максимальный возраст')),
                ('age_display', models.CharField(blank=True, max_length=50, null=True, verbose_name='Возраст (текстом, если диапазон)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Домашняя группа',
                'verbose_name_plural': 'Домашние группы',
                'ordering': ['order', 'district', 'day'],
            },
        ),
    ]
