# Generated by Django 4.2.30 on 2026-09-12 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0016_homegroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('hero', 'Главный экран (Hero)'), ('text', 'Текстовый блок'), ('speakers', 'Сетка спикеров'), ('schedule', 'Расписание'), ('registration', 'Форма регистрации/Билеты'), ('image_gallery', 'Галерея изображений')], max_length=50, verbose_name='Тип блока')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('content', models.JSONField(blank=True, default=dict, help_text='Данные блока (заполняется через интерфейс админки)', verbose_name='Контент блока')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='church_app.event', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Блок лендинга',
                'verbose_name_plural': 'Блоки лендингов',
                'ordering': ['order'],
            },
        ),
    ]
