# Generated by Django 4.2.30 on 2026-09-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0019_alter_news_options_news_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='kidscontent',
            name='rutube_url',
            field=models.URLField(blank=True, null=True, verbose_name='Rutube ссылка'),
        ),
        migrations.AddField(
            model_name='kidscontent',
            name='vk_url',
            field=models.URLField(blank=True, null=True, verbose_name='VK Video ссылка'),
        ),
        migrations.AddField(
            model_name='video',
            name='vk_url',
            field=models.URLField(blank=True, null=True, verbose_name='VK Video ссылка'),
        ),
    ]
