# Generated by Django 4.2.30 on 2026-09-19 05:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('church_app', '0021_emailverificationotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayerrequest',
            name='category',
            field=models.CharField(choices=[('general', 'Общая нужда'), ('health', 'Здоровье и исцеление'), ('family', 'Семья и дети'), ('spiritual', 'Духовная жизнь'), ('finance', 'Работа и финансы'), ('thanks', 'Благодарность Богу')], default='general', max_length=30, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='Анонимная просьба'),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='supporters',
            field=models.ManyToManyField(blank=True, related_name='supported_prayers', to=settings.AUTH_USER_MODEL, verbose_name='Кто поддержал в молитве'),
        ),
    ]
