# Generated by Django 4.2.30 on 2026-09-19 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('church_app', '0022_prayerrequest_category_prayerrequest_is_anonymous_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Тема/Заголовок')),
                ('content', models.TextField(verbose_name='Текст откровения/свидетельства')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичное')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Анонимное')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Откровение/Свидетельство',
                'verbose_name_plural': 'Откровения и свидетельства',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RevelationReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('amen', '🙏 Аминь'), ('glory', '❤️ Слава Богу'), ('fire', '🔥 Вдохновляет'), ('grace', '🕊️ Благодать')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revelation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='church_app.revelation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Реакция',
                'verbose_name_plural': 'Реакции',
                'unique_together': {('revelation', 'user', 'reaction_type')},
            },
        ),
    ]
