# Generated by Django 4.2.30 on 2026-09-19 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('church_app', '0023_revelation_revelationreaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Номер телефона')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram (@username или ссылка)')),
                ('vk', models.CharField(blank=True, max_length=100, verbose_name='ВКонтакте (ссылка или id/username)')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город / Район')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='О себе / Свидетельство')),
                ('home_group', models.CharField(blank=True, max_length=150, verbose_name='Домашняя группа')),
                ('baptism_date', models.DateField(blank=True, null=True, verbose_name='Дата крещения / духовный день рождения')),
                ('avatar_color', models.CharField(default='from-amber-400 to-amber-600', max_length=50, verbose_name='Цвет аватара')),
                ('is_public', models.BooleanField(default=True, verbose_name='Открытый профиль для прихожан')),
                ('notify_daily_verse', models.BooleanField(default=True, verbose_name='Стих дня каждое утро')),
                ('notify_prayer_answers', models.BooleanField(default=True, verbose_name='Ответы на молитвы')),
                ('notify_events', models.BooleanField(default=True, verbose_name='Церковные события')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='PrayerConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Связаны с')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_following', to=settings.AUTH_USER_MODEL, verbose_name='Кто молится')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_followers', to=settings.AUTH_USER_MODEL, verbose_name='За кого молится')),
            ],
            options={
                'verbose_name': 'Молитвенная связь',
                'verbose_name_plural': 'Молитвенные связи',
                'ordering': ['-created_at'],
                'unique_together': {('from_user', 'to_user')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteVerse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=150, verbose_name='Место Писания (напр. Иоанна 3:16)')),
                ('verse_text', models.TextField(verbose_name='Текст стиха')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Личная заметка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_verses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Любимый стих',
                'verbose_name_plural': 'Любимые стихи',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'reference')},
            },
        ),
    ]
