# Generated by Django 4.2.30 on 2026-09-19 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('church_app', '0024_userprofile_prayerconnection_favoriteverse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventregistration',
            options={'ordering': ['-registered_at'], 'verbose_name': 'Регистрация на событие', 'verbose_name_plural': 'Регистрации на события'},
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='event',
            name='is_conference',
            field=models.BooleanField(default=False, verbose_name='Является конференцией/лендингом'),
        ),
        migrations.AddField(
            model_name='event',
            name='paypal_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на PayPal'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_fee',
            field=models.CharField(blank=True, max_length=150, verbose_name='Регистрационное пожертвование (текст)'),
        ),
        migrations.AddField(
            model_name='event',
            name='sbp_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на пожертвование по СБП'),
        ),
        migrations.AddField(
            model_name='event',
            name='stream_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на трансляцию/материалы для участников'),
        ),
        migrations.AddField(
            model_name='event',
            name='support_telegram',
            field=models.CharField(blank=True, default='@krasnkate', max_length=100, verbose_name='Telegram куратора/поддержки'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Заметки администратора'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to='event_receipts/%Y/%m/', verbose_name='Чек об оплате/пожертвовании'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'На проверке чека'), ('confirmed', 'Подтверждено'), ('free', 'Бесплатное участие'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус оплаты'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Номер билета'),
        ),
        migrations.AlterField(
            model_name='eventblock',
            name='block_type',
            field=models.CharField(choices=[('hero', 'Главный экран (Hero)'), ('concept', 'Концепция / Манифест'), ('audience', 'Для кого эта школа / событие'), ('topics', 'Темы и модули обучения'), ('schedule', 'Расписание и формат'), ('speakers', 'Спикеры конференции'), ('pricing', 'Пожертвование и реквизиты'), ('registration', 'Форма регистрации'), ('faq', 'Часто задаваемые вопросы (FAQ)'), ('text', 'Произвольный текстовый блок'), ('image_gallery', 'Галерея изображений')], max_length=50, verbose_name='Тип блока'),
        ),
        migrations.AlterField(
            model_name='eventblock',
            name='content',
            field=models.JSONField(blank=True, default=dict, help_text='Данные блока (заполняется через CMS конструктор)', verbose_name='Контент блока'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='attended',
            field=models.BooleanField(default=False, verbose_name='Присутствовал'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='church_app.event', verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Регистрация подтверждена'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
