# Generated by Django 4.2.30 on 2026-09-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0025_alter_eventregistration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventblock',
            name='block_type',
            field=models.CharField(choices=[('hero', 'Главный экран (Hero) и баннер'), ('concept', 'Концепция / Манифест'), ('audience', 'Для кого эта школа / событие'), ('topics', 'Темы и модули обучения'), ('schedule', 'Расписание и формат'), ('speakers', 'Спикеры конференции'), ('pricing', 'Пожертвование и реквизиты'), ('registration', 'Форма регистрации'), ('faq', 'Часто задаваемые вопросы (FAQ)'), ('video', 'Видео / Трейлер'), ('reviews', 'Отзывы участников'), ('custom_html', 'Кастомный HTML / Код от ИИ'), ('text', 'Произвольный текстовый блок'), ('image_gallery', 'Галерея изображений')], max_length=50, verbose_name='Тип блока'),
        ),
    ]
