# Generated by Django 4.2.30 on 2026-09-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0026_alter_eventblock_block_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='theme_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Настройки темы и оформления визитки'),
        ),
    ]
