# Generated by Django 4.2.30 on 2026-09-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0027_event_theme_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobackground',
            name='video_url',
            field=models.CharField(blank=True, help_text='Например: https://kclc.ru/wp-content/uploads/2024/09/фон-на-сайт.mp4', max_length=500, verbose_name='Ссылка на MP4-видео'),
        ),
        migrations.AlterField(
            model_name='herobackground',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hero_backgrounds/', verbose_name='Изображение / Постер'),
        ),
        migrations.AlterField(
            model_name='herobackground',
            name='link_url',
            field=models.CharField(blank=True, help_text='Например: /events/onlajn-zvuki-nebes/ или https://...', max_length=500, verbose_name='Ссылка при клике (кнопка)'),
        ),
    ]
