# Generated by Django 4.2.30 on 2026-09-20 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('church_app', '0029_userprofile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название служения')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL slug')),
                ('category', models.CharField(choices=[('media', 'Медиа и Креатив'), ('worship', 'Музыка и Прославление'), ('hospitality', 'Гостеприимство и Порядок'), ('nextgen', 'Дети и Молодёжь'), ('care', 'Забота и Молитва'), ('social', 'Социальное служение'), ('admin', 'Организация и ивенты')], default='media', max_length=30, verbose_name='Категория служения')),
                ('icon', models.CharField(default='volunteer_activism', max_length=50, verbose_name='Иконка (Material Symbols)')),
                ('badge', models.CharField(blank=True, max_length=60, verbose_name='Бейдж/направление')),
                ('short_description', models.CharField(max_length=300, verbose_name='Краткое описание')),
                ('description', models.TextField(verbose_name='Подробное описание и задачи')),
                ('requirements', models.TextField(blank=True, verbose_name='Требования к волонтёру')),
                ('schedule_info', models.CharField(blank=True, max_length=200, verbose_name='Время и график служения')),
                ('leader_name', models.CharField(blank=True, max_length=150, verbose_name='Лидер служения')),
                ('leader_contact', models.CharField(blank=True, max_length=100, verbose_name='Telegram / телефон лидера')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ministries/', verbose_name='Баннер / фото служения')),
                ('gradient_css', models.CharField(default='from-blue-600/30 to-indigo-900/40', max_length=255, verbose_name='CSS градиент для фона')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Служение',
                'verbose_name_plural': 'Служения',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Онлайн формат'),
        ),
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта для карты'),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота для карты'),
        ),
        migrations.AddField(
            model_name='homegroup',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание группы'),
        ),
        migrations.AddField(
            model_name='homegroup',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта (Latitude)'),
        ),
        migrations.AddField(
            model_name='homegroup',
            name='leader_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Лидер группы'),
        ),
        migrations.AddField(
            model_name='homegroup',
            name='leader_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон лидера'),
        ),
        migrations.AddField(
            model_name='homegroup',
            name='leader_telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram лидера'),
        ),
        migrations.AddField(
            model_name='homegroup',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота (Longitude)'),
        ),
        migrations.CreateModel(
            name='MinistryApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя и фамилия')),
                ('phone', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('message', models.TextField(blank=True, verbose_name='Опыт, таланты или пожелания')),
                ('status', models.CharField(choices=[('new', 'Новая заявка'), ('contacted', 'Связались'), ('accepted', 'Принят в команду'), ('declined', 'Отклонена')], default='new', max_length=20, verbose_name='Статус заявки')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Заметки служителя / пастора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='church_app.ministry', verbose_name='Служение')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministry_applications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка на служение',
                'verbose_name_plural': 'Заявки на служение',
                'ordering': ['-created_at'],
            },
        ),
    ]
