# Generated by Django 4.2.30 on 2026-09-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0030_ministry_event_is_online_event_latitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.AddField(
            model_name='video',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
