# Generated by Django 4.2.30 on 2026-09-22 08:35

from django.db import migrations

def create_yandex_keys(apps, schema_editor):
    try:
        SocialApp = apps.get_model('socialaccount', 'SocialApp')
        Site = apps.get_model('sites', 'Site')
        
        # Get or create Yandex SocialApp
        yandex_app, created = SocialApp.objects.get_or_create(
            provider='yandex',
            defaults={'name': 'Yandex'}
        )
        yandex_app.client_id = '57209c88d425417782ba3ee6d626786f'
        yandex_app.secret = '21d1f0f10af649a8a638415902e49700'
        yandex_app.save()
        
        # Ensure it is linked to the current site (ID 1)
        try:
            site = Site.objects.get(id=1)
            yandex_app.sites.add(site)
        except Site.DoesNotExist:
            pass
    except LookupError:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0031_alter_video_options_video_published_at'),
        ('socialaccount', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_yandex_keys),
    ]
